$(document).ready(function(){
  $(".head1").click(function(){
    $("#text1").slideToggle("slow");
  });
  $(".head2").click(function(){
    $("#text2").slideToggle("slow");
  });
  $(".head3").click(function(){
    $("#text3").slideToggle("slow");
  });
  $(".head4").click(function(){
    $("#text4").slideToggle("slow");
  });
  $(".head5").click(function(){
    $("#text5").slideToggle("slow");
  });
  $(".head6").click(function(){
    $("#text6").slideToggle("slow");
  });
  $(".head7").click(function(){
    $("#text7").slideToggle("slow");
  });
  $(".head8").click(function(){
    $("#text8").slideToggle("slow");
  });
  $(".head9").click(function(){
    $("#text9").slideToggle("slow");
  });
  $(".head10").click(function(){
    $("#text10").slideToggle("slow");
  });
  
  $(".1a").click(function(){
    $("#text1a").slideToggle("slow");
  });
  $(".1b").click(function(){
    $("#text1b").slideToggle("slow");
  });
  $(".1c").click(function(){
    $("#text1c").slideToggle("slow");
  });
  $(".1d").click(function(){
    $("#text1d").slideToggle("slow");
  });
  $(".1e").click(function(){
    $("#text1e").slideToggle("slow");
  });
  $(".1f").click(function(){
    $("#text1f").slideToggle("slow");
  });
  $(".1g").click(function(){
    $("#text1g").slideToggle("slow");
  });
  $(".1h").click(function(){
    $("#text1h").slideToggle("slow");
  });
  $(".2a").click(function(){
    $("#text2a").slideToggle("slow");
  });
  $(".2b").click(function(){
    $("#text2b").slideToggle("slow");
  });
  $(".2c").click(function(){
    $("#text2c").slideToggle("slow");
  });
  $(".2d").click(function(){
    $("#text2d").slideToggle("slow");
  });
  $(".2e").click(function(){
    $("#text2e").slideToggle("slow");
  });
  $(".2f").click(function(){
    $("#text2f").slideToggle("slow");
  });
  $(".2g").click(function(){
    $("#text2g").slideToggle("slow");
  });
  $(".3a").click(function(){
    $("#text3a").slideToggle("slow");
  });
  $(".3b").click(function(){
    $("#text3b").slideToggle("slow");
  });
  $(".3c").click(function(){
    $("#text3c").slideToggle("slow");
  });
  $(".4a").click(function(){
    $("#text4a").slideToggle("slow");
  });
  $(".4b").click(function(){
    $("#text4b").slideToggle("slow");
  });
});
